---
kind: pipeline
type: exec
name: default

clone:
  depth: 25

steps:
  - name: submodules
    commands:
      - git submodule update --init --recursive --depth 25

  - name: arm64:rpi4
    commands:
      - make CTARGET=aarch64-unknown-linux-gnu package_rpi4
    
  - name: arm64:toolchain:master
    commands:
      # - make CTARGET=aarch64-unknown-linux-gnu package_toolchain
      - echo "test"
  - name: amd64:toolchain:master
    commands:
      # - make CTARGET=x86_64-multilib-linux-gnu package_toolchain

  - name: package
    commands:
      - make GENTOO_MIRRORS="http://mirror.netcologne.de/gentoo/" PACKAGE="sys-apps/ethtool" package_package
    