#!/bin/sh
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2021 Sartura Ltd.
#

# Script to enable updating UBI based systems using Systemd

RAMROOT=ramroot
TTYSHELL=ttyMSM0
FIRMWARE=upgrade.img

# Create our tmpfs folder to bind to
mkdir /$RAMROOT
# Mount it as tmpfs with size limit of 128MB
mount -n -t tmpfs -o size=128m none /$RAMROOT
# Create needed folders inside
cd /$RAMROOT
mkdir -p etc bin sbin lib var/lock
# Copy neccessary libs for UBI tools to work
cp /lib/* /$RAMROOT/lib
# Copy UBI tools
cp /usr/sbin/ubi* /$RAMROOT/sbin
# Copy U-boot envtools
cp /etc/fw_env.config /$RAMROOT/etc
cp /usr/bin/fw_printenv /$RAMROOT/sbin
cp /usr/bin/fw_setenv /$RAMROOT/sbin
# Copy upgrade scripts
cp /usr/upgrade/watchdog /$RAMROOT
cp /usr/upgrade/upgrader /$RAMROOT
# Copy firmware image
cp /tmp/$FIRMWARE /$RAMROOT
# Configure BusyBox init
echo "${TTYSHELL}::askfirst:-/bin/sh" >> /$RAMROOT/etc/inittab
echo "::restart:/bin/init" >> /$RAMROOT/etc/inittab
echo "::ctrlaltdel:/bin/reboot" >> /$RAMROOT/etc/inittab
echo "::once:/watchdog" >> /$RAMROOT/etc/inittab
echo "::once:/upgrader" >> /$RAMROOT/etc/inittab
# Install staticly compiled BusyBox to bin
cp /bin/busybox /$RAMROOT
chmod +x busybox
./busybox --install bin
rm busybox
# Remove share property from rootfs binding
unshare -m