#!/bin/sh
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2021 Sartura Ltd.
#

set -e

board=$(strings /proc/device-tree/compatible | head -1)

find_mtd_index() {
	local PART="$(grep "\"$1\"" /proc/mtd | awk -F: '{print $1}')"
	local INDEX="${PART##mtd}"

	echo ${INDEX}
}

find_mtd_part() {
	local INDEX=$(find_mtd_index "$1")
	local PREFIX=/dev/mtdblock

	[ -d /dev/mtdblock ] && PREFIX=/dev/mtdblock/
	echo "${INDEX:+$PREFIX$INDEX}"
}

find_mtd_chardev() {
	local INDEX=$(find_mtd_index "$1")
	local PREFIX=/dev/mtd

	[ -d /dev/mtd ] && PREFIX=/dev/mtd/
	echo "${INDEX:+$PREFIX$INDEX}"
}

caldata_die() {
	echo "caldata: " "$*"
	exit 1
}

caldata_extract() {
	local part=$1
	local offset=$(($2))
	local count=$(($3))
	local mtd

	mtd=$(find_mtd_chardev $part)
	[ -n "$mtd" ] || caldata_die "no mtd device found for partition $part"

	dd if=$mtd of=/lib/firmware/$FIRMWARE iflag=skip_bytes bs=$count skip=$offset count=1 2>/dev/null || \
		caldata_die "failed to extract calibration data from $mtd"
}

FIRMWARE="ath10k/pre-cal-ahb-a000000.wifi.bin"
case "$board" in
	edgecore,ecw5211-l-t)
		caldata_extract "ART" 0x1000 0x2f20
		;;
	*)
		echo "Unsupported board:" $board
		exit 1
	;;
esac

FIRMWARE="ath10k/pre-cal-ahb-a800000.wifi.bin"
case "$board" in
	edgecore,ecw5211-l-t)
		caldata_extract "ART" 0x5000 0x2f20
		;;
	*)
		echo "Unsupported board:" $board
		exit 1
	;;
esac
